using FealtedByEsra.Entity.Entities;
using FluentValidation;

namespace FealtedByEsra.BAL.Validations.CommentValidate
{
    public class CommentValidation : AbstractValidator<Comment>
    {
        public CommentValidation()
        {
            RuleFor(c => c.Title).NotEqual("am").NotEqual("Am").NotEqual("aM").NotEqual("AM").NotEqual("sik").NotEqual("Sik").NotEqual("sİk").NotEqual("siK").NotEqual("Sİk").NotEqual("SiK").NotEqual("sİK").NotEqual("SİK").NotEqual("sikiş").NotEqual("sikiŞ").NotEqual("sikİŞ").NotEqual("siKiŞ").NotEqual("sİkiŞ").NotEqual("SikiŞ").NotEqual("Sİkiş").NotEqual("SiKiş").NotEqual("amk").NotEqual("Amk").NotEqual("Aq").NotEqual("aq").NotEqual("aMk").NotEqual("AMk").NotEqual("AMK").NotEqual("seks").NotEqual("Seks").NotEqual("sEks").NotEqual("SekS").NotEqual("Amcık").NotEqual("amcik").NotEqual("amina koyim").NotEqual("amina kodum").NotEqual("amina korum").NotEqual("amini sikerim").NotEqual("sikerim").NotEqual("Siktir").NotEqual("siktir").NotEqual("pezevenk").NotEqual("orospu").NotEqual("oç").NotEqual("o.ç").NotEqual("O.ç").NotEqual("OÇ").NotEqual("göt").NotEqual("Göt").NotEqual("piç").NotEqual("Piç").NotEqual("pic").NotEqual("Pic").NotEqual("yarrak").NotEqual("Yarrak").NotEqual("Pipi").NotEqual("pipi").NotEqual("orospu cocugu").NotEqual("orospu çocuğu").Length(2, 100).NotEqual("Orospu Cocugu").NotEqual("Orospu Çocuğu").NotEqual("Orospu").WithMessage("Başlığınızı kontrol ediniz!");

            RuleFor(c => c.FirstAndLastName).NotEqual("am").NotEqual("Am").NotEqual("aM").NotEqual("AM").NotEqual("sik").NotEqual("Sik").NotEqual("sİk").NotEqual("siK").NotEqual("Sİk").NotEqual("SiK").NotEqual("sİK").NotEqual("SİK").NotEqual("sikiş").NotEqual("sikiŞ").NotEqual("sikİŞ").NotEqual("siKiŞ").NotEqual("sİkiŞ").NotEqual("SikiŞ").NotEqual("Sİkiş").NotEqual("SiKiş").NotEqual("amk").NotEqual("Amk").NotEqual("Aq").NotEqual("aq").NotEqual("aMk").NotEqual("AMk").NotEqual("AMK").NotEqual("seks").NotEqual("Seks").NotEqual("sEks").NotEqual("SekS").NotEqual("Amcık").NotEqual("amcik").NotEqual("amina koyim").NotEqual("amina kodum").NotEqual("amina korum").NotEqual("amini sikerim").NotEqual("sikerim").NotEqual("Siktir").NotEqual("siktir").NotEqual("pezevenk").NotEqual("orospu").NotEqual("oç").NotEqual("o.ç").NotEqual("O.ç").NotEqual("OÇ").NotEqual("göt").NotEqual("Göt").NotEqual("piç").NotEqual("Piç").NotEqual("pic").NotEqual("Pic").NotEqual("yarrak").NotEqual("Yarrak").NotEqual("Pipi").NotEqual("pipi").NotEqual("orospu cocugu").NotEqual("orospu çocuğu").Length(2, 100).NotEqual("Orospu Cocugu").NotEqual("Orospu Çocuğu").NotEqual("Orospu").NotEmpty().WithMessage("İsminizi kontrol ediniz!");

            RuleFor(c => c.Content).NotEqual("am").NotEqual("Am").NotEqual("aM").NotEqual("AM").NotEqual("sik").NotEqual("Sik").NotEqual("sİk").NotEqual("siK").NotEqual("Sİk").NotEqual("SiK").NotEqual("sİK").NotEqual("SİK").NotEqual("sikiş").NotEqual("sikiŞ").NotEqual("sikİŞ").NotEqual("siKiŞ").NotEqual("sİkiŞ").NotEqual("SikiŞ").NotEqual("Sİkiş").NotEqual("SiKiş").NotEqual("amk").NotEqual("Amk").NotEqual("Aq").NotEqual("aq").NotEqual("aMk").NotEqual("AMk").NotEqual("AMK").NotEqual("seks").NotEqual("Seks").NotEqual("sEks").NotEqual("SekS").NotEqual("Amcık").NotEqual("amcik").NotEqual("amina koyim").NotEqual("amina kodum").NotEqual("amina korum").NotEqual("amini sikerim").NotEqual("sikerim").NotEqual("Siktir").NotEqual("siktir").NotEqual("pezevenk").NotEqual("orospu").NotEqual("oç").NotEqual("o.ç").NotEqual("O.ç").NotEqual("OÇ").NotEqual("göt").NotEqual("Göt").NotEqual("piç").NotEqual("Piç").NotEqual("pic").NotEqual("Pic").NotEqual("yarrak").NotEqual("Yarrak").NotEqual("Pipi").NotEqual("pipi").NotEqual("orospu cocugu").NotEqual("orospu çocuğu").Length(1, 2000).NotEmpty().NotEqual("Orospu Cocugu").NotEqual("Orospu Çocuğu").NotEqual("Orospu").WithMessage("İçeriğinizi kontrol ediniz!");

            RuleFor(c => c.Email).EmailAddress().NotEqual("am").NotEqual("Am").NotEqual("aM").NotEqual("AM").NotEqual("sik").NotEqual("Sik").NotEqual("sİk").NotEqual("siK").NotEqual("Sİk").NotEqual("SiK").NotEqual("sİK").NotEqual("SİK").NotEqual("sikiş").NotEqual("sikiŞ").NotEqual("sikİŞ").NotEqual("siKiŞ").NotEqual("sİkiŞ").NotEqual("SikiŞ").NotEqual("Sİkiş").NotEqual("SiKiş").NotEqual("amk").NotEqual("Amk").NotEqual("Aq").NotEqual("aq").NotEqual("aMk").NotEqual("AMk").NotEqual("AMK").NotEqual("seks").NotEqual("Seks").NotEqual("sEks").NotEqual("SekS").NotEqual("Amcık").NotEqual("amcik").NotEqual("amina koyim").NotEqual("amina kodum").NotEqual("amina korum").NotEqual("amini sikerim").NotEqual("sikerim").NotEqual("Siktir").NotEqual("siktir").NotEqual("pezevenk").NotEqual("orospu").NotEqual("oç").NotEqual("o.ç").NotEqual("O.ç").NotEqual("OÇ").NotEqual("göt").NotEqual("Göt").NotEqual("piç").NotEqual("Piç").NotEqual("pic").NotEqual("Pic").NotEqual("yarrak").NotEqual("Yarrak").NotEqual("Pipi").NotEqual("pipi").NotEqual("orospu cocugu").NotEqual("orospu çocuğu").NotEqual("Orospu Cocugu").NotEqual("Orospu Çocuğu").NotEqual("Orospu").WithMessage("Email adresinizi kontrol ediniz!");
        }
    }
}
